import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./styles/globals.scss";
import "./styles/variables.scss";
import { ReactNode } from "react";
import Header from "@/widgets/Header/Header";
import styles from './layout.module.scss';

const inter = Inter({
  variable: "--inter",
  weight: ["400", "500"],
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "XP Journal",
  // TODO переписать description
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru" className={inter.className}>
      <body>
        <Header />
        <main className={styles.main}>{children}</main>
      </body>
    </html>
  );
}
