import type { Metadata } from "next";
import { Noto_Sans_Mono } from "next/font/google";
import "./styles/globals.scss";
import "./styles/variables.scss";
import { ReactNode } from "react";
import Header from '@/widgets/Header/Header'

const motoSansMono = Noto_Sans_Mono({
  variable: "--font-moto-sans",
  weight: ["400", "500"],
  subsets: ["cyrillic", "latin"],
});

export const metadata: Metadata = {
  title: "XP Journal",
  // TODO переписать description
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: ReactNode;
}>) {
  return (
    <html lang="ru" className={motoSansMono.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  );
}
